# Configure sitewide settings
amazon: httpedwardc07-20
gtm_username: 'GTM-TTTNZWJ'
url: https://edlatimore.com
permalink: /:title/
timezone: America/New_York # List of time zones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
lang: en-us

# Configure site collections
collections:
  posts:
    permalink: /:title/
    output: true
  products:
    permalink: /products/:title/
    output: true
  resources:
    permalink: /resources/:title/
    output: true
  category_pages:
    permalink: /:title/
    output: true

# Configure collection defaults
defaults:
  - scope:
      path: ''
    values:
      layout: general
      image: /assets/images/thumbnails/1-default.jpg
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: post
      seo:
        type: BlogPosting

# Build settings
destination: _site
source: site
include: ['.htaccess', '_redirects']
data_dir: _data
includes_dir: _1-includes
layouts_dir: _2-layouts
uploads_dir: ../assets/images
keep_files:
  - css
  - assets
kramdown:
  smart_quotes: ['lsquo', 'rsquo', 'ldquo', 'rdquo']
plugins:
  - jekyll-paginate-v2
  - jekyll-include-cache
  - jekyll-responsive-image
  - jekyll-twitter-plugin

# Plugin settings
responsive_image:
  template: _1-includes/partials/image.html
  sizes:
    - width: 100
    - width: 640
    - width: 800
    - width: 1280
  strip: true
  base_path: assets/images
  output_path_format: assets/images/%{dirname}/%{filename}-%{width}.%{extension}
  save_to_source: false
  cache: false

pagination:
  enabled: true
  sort_reverse: true
  debug: false
  per_page: 15
  permalink: /:num/
  title: :title (page :num)
  trail:
    before: 3
    after: 3